{% set name = "resample" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/resample-{{ version }}.tar.gz
  sha256: 4bb4780340b83cc9097b2ba2f5d5b81a52dd1bbd40689ad80dd0437addb40b22

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - numpy >=1.21
    - scipy >=1.10

test:
  source_files:
    - tests
  requires:
    - pytest
    - pip
  imports:
    - resample
  commands:
    - python -m pytest tests
    - pip check

about:
  home: https://github.com/scikit-hep/resample
  summary: Tools for randomization-based inference in Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsaxton
    - HDembinski
    - conda-forge/scikit-hep
